order:
  - new_item: true
    item: Google
    href: https://mrdoob.com/projects/chromeexperiments/google-gravity/
    icon: mdi:earth
    target: _blank
    order: 0
  - item: overview
    order: 1
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 2
  - new_item: true
    item: Entities
    href: "/config/entities"
    icon: mdi:hexagon-multiple
    order: 3
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 4
  - item: hacs
    order: 5
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: config
    bottom: true
    order: 6
  - new_item: true
    item: Server Controls
    href: "/config/server_control"
    icon: mdi:server
    bottom: true
    order: 7
  - item: activity
    bottom: true
    order: 8
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 9
  - new_item: true
    item: developer tools
    name: Dev tools
    icon: mdi:tools
    href: "/config/developer-tools"
    bottom: true
    order: 10
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media
    hide: true
exceptions:
  - user:
    - Jim Hawkins
    - Long John Silver
    order:
      - new_item: true
        item: Updates
        href: "/config/updates"
        icon: mdi:update
  - user: Palaus
    extend_from: base
    order:
      - item: history
        order: 11
      - item: media
        order: 12
id: example_yaml (remove this from your config or replace with any other string)